#!/bin/bash
SUFFIX="-gc"
PROFILES_DIR="${FOXER_PROFILES:=$HOME/profiles/browsers}"

PROFILE_NAME=$1
PROFILE_PATH="${PROFILES_DIR}/${PROFILE_NAME}${SUFFIX}"

if [[ -z "$1" ]]; then
     echo "You need to provide the name of the profile"
     echo
     echo "Usage:"
     echo "   chromer PROFILE_NAME"
     exit
fi

# if not exists ${PROFILE_PATH}
if [[ ! -e $PROFILE_PATH ]]; then
   mkdir -p $PROFILE_PATH
fi

google-chrome --user-data-dir="${PROFILE_PATH}"
