#!/bin/bash
SUFFIX="-ff"
PROFILES_DIR="${FOXER_PROFILES:=$HOME/profiles/browsers}"

PROFILE_NAME=$1
PROFILE_PATH="${PROFILES_DIR}/${PROFILE_NAME}${SUFFIX}"

if [[ -z "$1" ]]; then
     echo "You need to provide the name of the profile"
     echo
     echo "Usage:"
     echo "   foxer PROFILE_NAME"
     exit
fi

# if not exists ${PROFILE_PATH}
if [[ ! -e $PROFILE_PATH ]]; then
   echo "No path, building a profile"
   firefox -no-remote -CreateProfile "${PROFILE_NAME} ${PROFILE_PATH}"
fi

firefox -no-remote -P "${PROFILE_NAME}"
