#!/bin/bash
SUFFIX="-ff"
PROFILES_DIR="${GLOBAL_PROFILES:=$HOME/profiles/browsers}"

PROFILE_NAME=$1
PROFILE_PATH="${PROFILES_DIR}/${PROFILE_NAME}${SUFFIX}"

# if not exists ${PROFILE_PATH}
if [[ ! -e $PROFILE_PATH ]]; then
   echo "No path, building a profile"
   firefox -no-remote -CreateProfile "${PROFILE_NAME} ${PROFILE_PATH}"
fi

# if passed file with urls
shift 1
URLS=$@

if [[ $PROFILE_NAME == $URLS ]];then
    URLS=""
fi
firefox -no-remote -P "${PROFILE_NAME}" $URLS
